---
title: "Untitled"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(tm)
library(glue)

data_raw <-
  read.csv("https://raw.githubusercontent.com/hadley/mexico-mortality/cdda7ea2a010a6edbd1ba5013d00696a2336591d/disease/icd-10.csv", stringsAsFactors = F) %>%
  rename(
    code = Code,
    description = ICD.Title
  ) %>%
  mutate(description = gsub(" and ", " & ", description))

get_categories_high <-
  data_raw %>%
  filter(grepl("-", code) & grepl("\\.", description)) %>%
  mutate(
    level_1 = gsub(". .*", "", description),
    code_3 = substr(code, 1, 3)
  ) %>%
  rename(label_1 = description) %>%
  select(-code)

get_categories_low <-
  data_raw %>%
  filter(grepl("-", code) & !grepl("\\.", description)) %>%
  mutate(
    level_2 = gsub(". .*", "", code),
    code_3 = substr(code, 1, 3)
  ) %>%
  rename(label_2 = description) %>%
  select(-code)

get_categories_3 <-
  data_raw %>%
  filter(nchar(code) == 3) %>%
  rename(
    code_3 = code,
    C3_text = description
  )

all_combos <-
  expand.grid(
    C1 = LETTERS,
    N1 = 0:9,
    N2 = 0:9, KEEP.OUT.ATTRS = F, stringsAsFactors = F
  ) %>%
  mutate(code_3 = paste0(C1, N1, N2)) %>%
  arrange(code_3) %>%
  left_join(get_categories_high) %>%
  left_join(get_categories_low) %>%
  left_join(get_categories_3) %>%
  fill(level_1, label_1, level_2, label_2, C3_text)
```

https://www.cob.cms.hhs.gov/Section111/assets/section111/Section111ValidICD10-2018.txt
```{r}
data_cdc <-
  read_fwf(
    "icd10cm_codes_2020.txt",
    fwf_widths(c(8, 300), c("original", "description"))
  ) %>%
  mutate(
    code_3 = str_sub(original, 1, 3),
    code = paste0(code_3, ".", str_sub(original, 4))
  ) %>%
  select(original, code_3, code, description)

get_words <-
  tibble(word = tm::stopwords()) %>%
  filter(!word %in%
    c(
      "open", "part",
      "right",
      "one", "two", "three", "four", "five", "six", "seven", "eight", "nine"
    )) %>%
  mutate(word = gsub("'", "", word)) %>%
  distinct(word)

remove_words <- paste(c(get_words$word, "unspecified", "encounter"), collapse = "|")

step_1 <-
  data_cdc %>%
  # filter(str_detect(code, "V30")) %>%
  left_join(all_combos) %>%
  arrange(code) %>%
  mutate(
    D1 = substr(code, 5, 5),
    D2 = substr(code, 6, 6),
    D3 = substr(code, 7, 7),
    D4 = substr(code, 8, 8),
    code_5 = substr(code, 1, 5),
    code_6 = substr(code, 1, 6),
    code_7 = substr(code, 1, 7),
    code_8 = substr(code, 1, 8)
  ) %>%
  mutate(
    description = tolower(description),
    description2 = str_replace_all(description, "[^[:alnum:] ]", "")
  ) %>%
  mutate(
    search_base = 
      str_replace_all(description2, glue("\\b({remove_words})\\b"), "") %>%
      str_replace_all("\\s+", " ") %>% 
      trimws()
  ) %>%
  select(original, description, C1, N1, N2, D1, D2, D3, D4, starts_with("code_"), everything())


tail(step_1)

#write.csv(step_1, "remove stop words from description.csv", row.names = F)
```

```{r}
filter(step_1, str_detect(code, "E83.3")) %>% select(search_base)

each_word <-
  step_1 %>%
  # filter(str_detect(code, "E83")) %>%
  select(starts_with("code"), D4, search_base) %>%
  unnest(word = str_split(search_base, " ")) %>%
  filter(word != "") %>%
  group_by(code) %>%
  mutate(ord = row_number()) %>%
  ungroup()


c5 <-
  each_word %>%
  group_by(code_5, word) %>%
  summarise(n = n()) %>%
  filter(n == max(n)) %>%
  mutate(c5_phrase = paste(word, collapse = " ")) %>%
  ungroup() %>%
  mutate(
    c5_lookup = str_replace_all(c5_phrase, "\\s", "|"),
    c5_lookup = paste0("\\b(", c5_lookup, ")\\b")
  ) %>%
  distinct(code_5, c5_phrase, c5_lookup)

c6 <-
  each_word %>%
  # filter(str_detect(code_3, "E83")) %>% #E83 is failing
  left_join(select(c5, code_5, c5_lookup)) %>%
  filter(!str_detect(word, c5_lookup)) %>%
  group_by(code_6, word) %>%
  summarise(n = n()) %>%
  filter(n == max(n)) %>%
  mutate(c6_phrase = paste(word, collapse = " ")) %>%
  ungroup() %>%
  mutate(
    c6_lookup = str_replace_all(c6_phrase, "\\s", "|"),
    c6_lookup = paste0("\\b(", c6_lookup, ")\\b")
  ) %>%
  distinct(code_6, c6_phrase, c6_lookup)

c8 <-
  each_word %>%
  left_join(select(c5, code_5, c5_lookup)) %>%
  left_join(select(c6, code_6, c6_lookup)) %>%
  filter(
    !str_detect(word, c5_lookup),
    !str_detect(word, c6_lookup)
  ) %>%
  group_by(code_5, D4, word) %>%
  summarise(n = n()) %>%
  filter(n == max(n)) %>%
  mutate(c8_phrase = paste(word, collapse = " ")) %>%
  ungroup() %>%
  mutate(
    c8_lookup = str_replace_all(c8_phrase, "\\s", "|"),
    c8_lookup = paste0("\\b(", c8_lookup, ")\\b")
  ) %>%
  distinct(code_5, D4, c8_phrase, c8_lookup)


c7 <-
  each_word %>%
  left_join(select(c5, code_5, c5_lookup)) %>%
  left_join(select(c6, code_6, c6_lookup)) %>%
  left_join(select(c8, code_5, D4, c8_lookup)) %>%
  filter(
    !str_detect(word, c5_lookup),
    !str_detect(word, c6_lookup),
    !str_detect(word, c8_lookup)
  ) %>%
  group_by(code_7, word) %>%
  summarise(n = n()) %>%
  filter(n == max(n)) %>%
  mutate(c7_phrase = paste(word, collapse = " ")) %>%
  ungroup() %>%
  mutate(
    c7_lookup = str_replace_all(c7_phrase, "\\s", "|"),
    c7_lookup = paste0("\\b(", c7_lookup, ")\\b")
  ) %>%
  distinct(code_7, c7_phrase, c7_lookup)

results <-
  step_1 %>%
  filter(code %in% each_word$code) %>%
  select( #-starts_with("level"), 
    #       -starts_with("label"),
    -description2
  ) %>%
  left_join(select(c5, code_5, c5_phrase)) %>%
  left_join(select(c6, code_6, c6_phrase)) %>%
  left_join(select(c7, code_7, c7_phrase)) %>%
  left_join(select(c8, code_5, D4, c8_phrase))

final <-
  results %>% 
  select(
    ICD10_RAW = original,
    ICD10_CD = code,
    FULL_DESCRIPTION = description,
    CHAR_1 = C1,
    CHAR_2 = N1,
    CHAR_3 = N2,
    CHAR_5 = D1,
    CHAR_6 = D2,
    CHAR_7 = D3,
    CHAR_8 = D4,
    FIRST_3 = code_3,
    FIRST_5 = code_5,
    FIRST_6 = code_6,
    FIRST_7 = code_7,
    FIRST_8 = code_8,
    HIGH_LEVEL = level_1,
    HIGH_LEVEL_TEXT = label_1,
    SUB_LEVEL = level_2,
    SUB_LEVEL_TEXT = label_2,
    LEFTHAND_TEXT = C3_text,
    RIGHTHAND_TEXT = search_base,
    CHAR_5_TEXT = c5_phrase,
    CHAR_6_TEXT = c6_phrase,
    CHAR_7_TEXT = c7_phrase,
    CHAR_8_TEXT = c8_phrase
  )


filter(final, str_detect(ICD10_CD, "S42.42")) %>%
  select(matches("\\d_TEXT")) %>%
  head()


write_csv(final, "first_pass.csv", na = ".")
```








Not using
```{r}
step_2 <-
  step_1 %>%
  group_by(code_5, D4) %>%
  mutate(
    search_base2 = lag(search_base, default = lead(search_base)),
    search_base2 = gsub("\\s", "|", search_base2)
  ) %>%
  ungroup() %>%
  rowwise() %>%
  mutate(
    different_8 = gsub(search_base2, "", search_base),
    same_8 = gsub(different_8, "", search_base)
  ) %>%
  ungroup() %>%
  group_by(code_5) %>%
  mutate(
    search_base2 = lag(search_base, default = lead(search_base)),
    search_base2 = gsub("\\s", "|", search_base2)
  ) %>%
  ungroup() %>%
  rowwise() %>%
  mutate(
    different_5 = gsub(search_base2, "", search_base),
    same_5 = gsub(different_5, "", search_base)
  ) %>%
  ungroup()
```

